--- # Install ELK software
- name: Running apt-get update
  apt: update_cache=yes

- name: Check Oracle license
  shell: /usr/bin/debconf-show oracle-java8-installer | awk '/accepted-oracle-license/{print $NF}'

- name: Accept Oracle license
  shell: echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 select true' | /usr/bin/debconf-set-selections

- name: Installing required software using apt-get
  apt: name={{ item }} state=present
  with_items:
   - apache2-utils
   - athena-jot
   - elasticsearch
   - geoip-database-contrib
   - git
   - htop
   - isc-dhcp-server
   - kibana
   - logstash 
   - logstash-forwarder
   - nginx
   - ngrep
   - oracle-java8-installer
   - python-geoip
   - python-mysqldb
   - python-passlib
   - python-pip
   - python-twisted
   - tcpdump
   - tcpflow
   - tree
   - tmux
   - vim
   - wget
   - whois

- name: Installing required software using pip
  pip: name={{ item }} state=present
  with_items:
    - geoip2
    - requests
