---
# Converts a Ubuntu into a honeypot router
- name: Starting Bifrozt setup
  hosts: bifrozt
  remote_user: root
  no_log: True
  roles:
   - software
   - system
   - network
   - honssh
   - tools
   - cleanup
