---
# This playbok will deploy bifrozt

- name: Create ssh conf file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config.bifrozt
  notify: 
  - restart ssh
  
- name: Create DHCP conf file
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf.bifrozt

  
- name: Create /etc/default/isc-dhcp-server file
  template: src=isc-dhcp-server.j2 dest=/etc/default/isc-dhcp-server.bifrozt
  notify:
  - restart dhcp

- name: Create iptables in logrotate.d
  template: src=iptables.j2 dest=/etc/logrotate.d/iptables.bifrozt

- name: Create sysctl.conf
  template: src=sysctl.conf.j2 dest=/etc/sysctl.conf.bifrozt

- name: Create interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces.bifrozt
  
- name: Create ipv4hater
  template: src=ipv4hater.j2 dest=/etc/network/ipv4hater.bifrozt
  
- name: Create ipv6hater
  template: src=ipv6hater.j2 dest=/etc/network/ipv6hater.bifrozt  
 
- name: Create 13-iptables in rsyslog.d
  template: src=13-iptables.j2 dest=/etc/rsyslog.d/13-iptables.bifrozt  

- name: Create root on /var/spool/cron/crontabs/
  template: src=root.j2 dest=/var/spool/cron/crontabs/root.bifrozt 
