---
# This playbok will deploy bifrozt

- name: Create ssh conf file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config.bifrozt
  notify: 
  - restart ssh
  
- name: Create DHCP conf file
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf.bifrozt

  
- name: Create /etc/default/isc-dhcp-server file
  template: src=isc-dhcp-server.j2 dest=/etc/default/isc-dhcp-server.bifrozt
  notify:
  - restart dhcp
